# Generated by Django 2.2 on 2021-05-24 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('priority', models.IntegerField(choices=[(1, 'Highest'), (2, 'High'), (3, 'Low'), (4, 'Lowest')], db_index=True, default=4)),
            ],
        ),
    ]
